spring:
  datasource:
    #Mysql
    url: jdbc:mysql://localhost:3306/pet?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      max-active: 20
      initial-size: 1
      max-wait: 60000
    dbcp2:
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  #开启mybatis驼峰命名
  configuration:
    map-underscore-to-camel-case: true
  #mapper文件所在位置
  mapper-locations: classpath:mappers/**/*.xml
#设置编码
server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
#控制台打印sql
logging:
  level:
    com:
      ecnu:
        edu:
          petuser:
            dao: debug
# 配置pageHelper参数
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql