spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  #开启mybatis驼峰命名
  configuration:
    map-underscore-to-camel-case: true
  #mapper文件所在位置
  mapper-locations: classpath*:mappers/**/*.xml

#设置编码
server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

# 配置pageHelper参数
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 文件路径
file:
  root-path: E:\pet\file\
  upload-dir: upload

#swagger
swagger:
  base-package: com.ecnu.edu

#控制台打印sql
logging:
  level:
    com:
      ecnu:
        edu: debug

# 微服务名称
pet:
  service:
    name:
      pet-sso: pet-sso
      pet-business: pet-business