spring:
  application:
    name: pet-gateway
    instance_id: localhost

server:
  port: 8002

# Eureka相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 60  # 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id}:${server.port}

# 添加ribbon的超时时间设置
# 负载均衡
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

# 路由
zuul:
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000

# 熔断器
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 100000

# jwt
jwt:
  issuer: leoqin
  # 1天
  expiration: 86400000
  # 7天
  expirationRemember: 604800000
  # salt
  secret: 49UF72vSkj-sA4aHHiYN5eoZ9Nb4w5Vb45PsLF7x_NY
  # jwt id(避免重放攻击)
  id: 71184501122-pet_ecnu_edu